version: "3.8"
services:
  db:
    container_name: db_server
    # For Windows ||||
    #image: mysql:8.1
    # For Windows ||||
    # For Mac ||||
    image: mariadb
    platform: linux/amd64
    # For Mac ||||
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # For Mac ||||
      - ./mysql:/var/lib/mysql
      # For Mac ||||
      # For windows
      #- bddata:/var/lib/mysql
      #- ./database/:/docker-entrypoint-initdb.d
      # For windows ||||
    networks:
      - platform
    # For Windows ||||
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # For Windows ||||
  django_api:
    container_name: api_server
    hostname: platform_apiserver
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - platform

  react_app:
    container_name: front_client
    hostname: platform_appfront
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - platform
    links:
      - django_api
# For Windows ||||
#volumes:
#  bddata:
# For Windows ||||
networks:
  platform:
    name: platform