version: "3.7"
services:
  db:
    container_name: db_server
    image: mysql:8.1
    #platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - bddata:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d
    networks:
      - platform
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  django_api:
    container_name: api_server
    hostname: platform_apiserver
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - platform

  react_app:
    container_name: front_client
    hostname: platform_appfront
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - platform
    links:
      - django_api

volumes:
  bddata:

networks:
  platform:
    name: platform